name: find_pe
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  logger: ^2.5.0
  toastification: ^3.0.1
  easy_localization: ^3.0.7+1
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.0
  icons_launcher: ^3.0.0
  flutter_svg: ^2.0.17
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  email_validator: ^3.0.0
  file_picker: ^9.0.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  http: ^1.3.0
  lottie: ^3.3.1
  card_loading: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  freezed: ^3.0.3
  json_serializable: ^6.9.4

icons_launcher:
  image_path: "assets/images/logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

